### PR TITLE
Add a naive bubble effect

### PR DESCRIPTION
**Pull request by Czajnikowski**
Maybe somebody will find it useful 🙃

https://github.com/twostraws/Inferno/assets/973682/6dfd53e3-c466-4720-9d9c-89467b4a2c3c

### CODE REVIEW

**Comment by twostraws** [comment]
This is really beautiful – great job! I'm going to merge it in now, but we need to come back to this for documentation in the README.

**Comment by Czajnikowski** [comment]
Will take a look at it tomorrow 🫡

**Comment by Czajnikowski** [comment]
Hey @Aayush9029 , I've seen that you added most of the images to the repo. What procedure did you follow in order to export rendered content? Sorry if I missed the instructions if there are any 🙏

**Comment by Aayush9029** [comment]
@Czajnikowski I made sure to centre the content and ensure that the image has a 1:1 ratio.

**Pull request merged**
