### PR TITLE
Add Shift and Genie/Suck transition effect

### PR DESCRIPTION
**Pull request by twodayslate**
https://github.com/twostraws/Inferno/assets/1085707/bd653899-9ade-4c0a-89ee-5f5d2d448fdb

Shift from: https://nerdyak.tech/development/2023/06/16/distortionEffect-with-Metal-shaders-for-better-transitions.html

Genie shader from: https://www.shadertoy.com/view/flyfRt

Future work: parameterize functions for more customizability

### CODE REVIEW

**Comment by twodayslate** [comment]
I have sent @altaha-ansari an email to verify

**Comment by twodayslate** [comment]
I have already tagged @izakpavel on X

**Comment by Aayush9029** [comment]
image

Seems like it's MIT. Getting a verbal confirmation is always a good idea though.

**Comment by twostraws** [comment]
Ah! Yes, that license has now been added. I think getting permission as well is a very good idea, particularly for code that is already written in Metal.

**Comment by twodayslate** [comment]
From @altaha-ansari via email:

> I hope this message finds you well. I'm delighted to see my work being utilized. I have added a License to my work on Shadertoy.
I appreciate your interest in the code, and I'm reaching out to kindly request that you honor the MIT License terms associated with it.

> As per the MIT License, you are free to use, modify, and distribute the code, but I would appreciate it if you could include the mentioned attribution in your project.

I have to rebase so can add a comment in the codebase and we can add his GitHub to the squash commit message as a thank you.

**Pull request closed without merging**
