### PR TITLE
[Fix] WelcomeView: Handle Dynamic Type & Orientation Changes

### PR DESCRIPTION
**Pull request by nickkohrn**
### Description
Allow `WelcomeView` to scroll so it can better handle Dynamic Type and orientation changes.

<details>
<summary>Preview Videos</summary>

https://github.com/twostraws/Inferno/assets/5864877/6b308760-06b9-4d07-aa20-b1edc59fcafa

https://github.com/twostraws/Inferno/assets/5864877/ef68709b-e1c1-4498-a52b-b2f1d67e5d67

</details>

### CODE REVIEW

**Comment by twostraws** [comment]
Sorry for taking so long to get to this! Thank you; this is an important improvement. Just to confirm: is the GeometryReader necessary?

**Comment by nickkohrn** [comment]
> Sorry for taking so long to get to this! Thank you; this is an important improvement. Just to confirm: is the GeometryReader necessary?

Hey Paul, no problem. You're quite busy!

The `GeometryReader` is probably not necessary, but using it in combination with `.frame(minHeight: geometry.size.height)` allows the content to be vertically centered within the `ScrollView` when the content isn't large enough to cause scrolling. 

If you'd like, I can replace the use of `GeometryReader` with a `ViewThatFits` and wrap a `VStack` to handle vertical centering when the content isn't large enough to scroll, and a `ScrollView` to handle scrolling when needed.

**Comment by nickkohrn** [comment]
@twostraws I went ahead and replaced `GeometryReader` with `ViewThatFits`, which I think is a better solution. Thanks for nudging me think about it a bit more.

**Comment by twostraws** [comment]
Thank you! This is great now 🙌

**Pull request merged**
